version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db

  scrapy:
    build: ./scraping
    container_name: games_scraper
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DATABASE: steam_market

  fastapi:
    build: ./app
    container_name: fastapi_server
    ports:
      - "8000:8000"
    depends_on:
      - mongo
